// <auto-generated />
using System;
using EzLabManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzLabManager.Data.Migrations
{
    [DbContext(typeof(EzLabDbContext))]
    partial class EzLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("EzLabManager.Models.ConsumableInboundRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsumableItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InboundById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InboundDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableItemId");

                    b.HasIndex("InboundById");

                    b.HasIndex("ConsumableItemId", "BatchNumber", "ExpirationDate");

                    b.ToTable("ConsumableInboundRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConsumableInboundRecords_Quantity_Positive", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName", "ModelName")
                        .IsUnique();

                    b.ToTable("ConsumableItems", (string)null);
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableOutboundRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("InboundRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutboundById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OutboundDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InboundRecordId");

                    b.HasIndex("OutboundById");

                    b.HasIndex("BatchNumber", "OutboundDate");

                    b.ToTable("ConsumableOutboundRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConsumableOutboundRecords_Quantity_Positive", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("EzLabManager.Models.LabTechnician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("LabTechnicians", (string)null);
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableInboundRecord", b =>
                {
                    b.HasOne("EzLabManager.Models.ConsumableItem", "ConsumableItem")
                        .WithMany("InboundRecords")
                        .HasForeignKey("ConsumableItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EzLabManager.Models.LabTechnician", "InboundBy")
                        .WithMany("InboundRecords")
                        .HasForeignKey("InboundById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumableItem");

                    b.Navigation("InboundBy");
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableOutboundRecord", b =>
                {
                    b.HasOne("EzLabManager.Models.ConsumableInboundRecord", "InboundRecord")
                        .WithMany("OutboundRecords")
                        .HasForeignKey("InboundRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EzLabManager.Models.LabTechnician", "OutboundBy")
                        .WithMany("OutboundRecords")
                        .HasForeignKey("OutboundById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InboundRecord");

                    b.Navigation("OutboundBy");
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableInboundRecord", b =>
                {
                    b.Navigation("OutboundRecords");
                });

            modelBuilder.Entity("EzLabManager.Models.ConsumableItem", b =>
                {
                    b.Navigation("InboundRecords");
                });

            modelBuilder.Entity("EzLabManager.Models.LabTechnician", b =>
                {
                    b.Navigation("InboundRecords");

                    b.Navigation("OutboundRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
